# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CytoElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('nodes', 'nodes'), ('edges', 'edges')], default='nodes', max_length=6)),
                ('selected', models.BooleanField(default=False)),
                ('selectable', models.BooleanField(default=True)),
                ('locked', models.BooleanField(default=False)),
                ('grabbable', models.BooleanField(default=True)),
                ('classes', models.CharField(blank=True, help_text='a space separated list of css class names for the element', max_length=250, null=True)),
                ('label', models.CharField(blank=True, help_text='if present, will be used as node label instead of id', max_length=50, null=True)),
                ('data_parent', models.ForeignKey(blank=True, help_text='indicates the compound node parent; blank/null => no parent', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='djcytoscape.CytoElement')),
                ('data_source', models.ForeignKey(blank=True, help_text='edge comes from this node', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='djcytoscape.CytoElement')),
                ('data_target', models.ForeignKey(blank=True, help_text='edge goes to this node', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='djcytoscape.CytoElement')),
            ],
        ),
        migrations.CreateModel(
            name='CytoScape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('container_element_id', models.CharField(default='cy', help_text="id of the html element where the graph's canvas will be placed", max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='cytoelement',
            name='scape',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djcytoscape.CytoScape'),
        ),
    ]
