# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djcytoscape', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CytoLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='cytoscape',
            name='edge_styles',
            field=models.TextField(blank=True, help_text='value1, key2: value2, ...', null=True),
        ),
        migrations.AddField(
            model_name='cytoscape',
            name='layout_name',
            field=models.CharField(default='random', help_text='layout name according to cytoscape API: http://js.cytoscape.org/#layouts', max_length=50),
        ),
        migrations.AddField(
            model_name='cytoscape',
            name='layout_options',
            field=models.TextField(blank=True, help_text='value1, key2: value2, ...', null=True),
        ),
        migrations.AddField(
            model_name='cytoscape',
            name='node_styles',
            field=models.TextField(blank=True, help_text='value1, key2: value2, ...', null=True),
        ),
        migrations.AddField(
            model_name='cytoscape',
            name='parent_styles',
            field=models.TextField(blank=True, help_text='value1, key2: value2, ...', null=True),
        ),
    ]
